name: Beanstalk Workflow

on:
  push:
    branches:
      - master
      
env:
  AWS_REGION: us-east-1 
  S3_BUCKET: rico-projects-artifacts 
  EB_APPLICATION_NAME_STAGE: myapp 
  EB_ENVIRONMENT_NAME_PROD: myapp-env 
  EB_APPLICATION_NAME_DEV: myapp-stage 
  EB_ENVIRONMENT_NAME_STAGE: myapp-stage-env 
  PIPELINE_ID: ${{ github.run_id }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.EB_APPLICATION_NAME_STAGE }}
          IMAGE_TAG: ${{ env.PIPELINE_ID }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Create Dockerrun.aws.json
        run: |
          cat > Dockerrun.aws.json << EOF
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ steps.login-ecr.outputs.registry }}/${{ env.EB_APPLICATION_NAME_STAGE }}:${{ env.PIPELINE_ID }}",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 3000,
                "HostPort": 80
              }
            ]
          }
          EOF

      # - name: Generate ECS task definition file
      #   env:
      #     IMAGE_TAG: ${{ github.sha }}
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     run: |
      #       cat > task-def.json <<EOF
      #       {
      #         "family": "${TASK_FAMILY}",
      #         "networkMode": "awsvpc",
      #         "cpu": "256",
      #         "memory": "512",
      #         "requiresCompatibilities": ["FARGATE"],
      #         "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole",
      #         "containerDefinitions": [
      #           {
      #             "name": "${CONTAINER_NAME}",
      #             "image": "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}",
      #             "essential": true,
      #             "portMappings": [
      #               {
      #                 "containerPort": 3000,
      #                 "protocol": "tcp"
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #       EOF

      - name: Zip Artifacts
        run: |
          zip -r artifacts.zip .

      - name: Upload Artifacts to S3
        run: |
          aws s3 cp artifacts.zip s3://${{ env.S3_BUCKET }}/artifacts-${{ env.PIPELINE_ID }}.zip
          aws s3 cp Dockerrun.aws.json s3://${{ env.S3_BUCKET }}/Dockerrun.aws.json-${{ env.PIPELINE_ID }}

  deploy-dev:
    name: Development Deployment # Deploy to beanstalk from source
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME_DEV }} \
            --version-label ${{ env.PIPELINE_ID }} \
            --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="artifacts-${{ env.PIPELINE_ID }}.zip" \
            --description "Deployment from GitHub Actions - ${{ github.run_id }}"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ env.EB_APPLICATION_NAME_DEV }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME_STAGE }} \
            --version-label ${{ env.PIPELINE_ID }}

      - name: Wait for deployment to complete
        run: |
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ env.EB_APPLICATION_NAME_DEV }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME_STAGE }}

      # - name: Get deployment status
      #   run: |
      #     STATUS=$(aws elasticbeanstalk describe-environments \
      #       --application-name ${{ env.EB_APPLICATION_NAME_DEV }} \
      #       --environment-names ${{ env.EB_ENVIRONMENT_NAME_STAGE }} \
      #       --query "Environments[0].Status" \
      #       --output text)
      #     HEALTH=$(aws elasticbeanstalk describe-environments \
      #       --application-name ${{ env.EB_APPLICATION_NAME_DEV }} \
      #       --environment-names ${{ env.EB_ENVIRONMENT_NAME_STAGE }} \
      #       --query "Environments[0].Health" \
      #       --output text)
      #     echo "Deployment status: $STATUS"
      #     echo "Deployment health: $HEALTH"

  deploy-stage:
    name: Staging Deployment # Deploy to beanstalk from image
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APPLICATION_NAME_STAGE }} \
            --version-label ${{ env.PIPELINE_ID }} \
            --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="artifacts-${{ env.PIPELINE_ID }}.zip" \
            --description "Deployment from GitHub Actions - ${{ github.run_id }}"
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name ${{ env.EB_APPLICATION_NAME_STAGE }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME_PROD }} \
            --version-label ${{ env.PIPELINE_ID }}
      
      - name: Wait for deployment to complete
        run: |
          aws elasticbeanstalk wait environment-updated \
            --application-name ${{ env.EB_APPLICATION_NAME_STAGE }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME_PROD }}

      # - name: Get deployment status
      #   run: |
      #     STATUS=$(aws elasticbeanstalk describe-environments \
      #       --application-name ${{ env.EB_APPLICATION_NAME_STAGE }} \
      #       --environment-names ${{ env.EB_ENVIRONMENT_NAME_PROD }} \
      #       --query "Environments[0].Status" \
      #       --output text)
      #     HEALTH=$(aws elasticbeanstalk describe-environments \
      #       --application-name ${{ env.EB_APPLICATION_NAME_STAGE }} \
      #       --environment-names ${{ env.EB_ENVIRONMENT_NAME_PROD }} \
      #       --query "Environments[0].Health" \
      #       --output text)
      #     echo "Deployment status: $STATUS"

  deploy-to-ecs:
    name: Deploy to ECS (Production) # Deploy to ECS from image
    needs: [deploy-dev, deploy-stage]
    runs-on: ubuntu-latest

    env:
      # IMAGE_TAG: ${{ env.PIPELINE_ID }}
      CONTAINER_NAME: myapp-container
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER_NAME }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE_NAME }}
      TASK_FAMILY: myapp-task
      EXECUTION_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole
      TASK_DEF_ARN: arn:aws:ecs:us-east-1:381491850253:task-definition/myapp-task:2

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Create ECS task definition
      #   run: |
      #     cat > task-def.json <<EOF
      #     {
      #       "family": "${{ env.TASK_FAMILY }}",
      #       "networkMode": "awsvpc",
      #       "requiresCompatibilities": ["FARGATE"],
      #       "cpu": "256",
      #       "memory": "512",
      #       "executionRoleArn": "${{ env.EXECUTION_ROLE_ARN }}",
      #       "containerDefinitions": [
      #         {
      #           "name": "${{ env.CONTAINER_NAME }}",
      #           "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.EB_APPLICATION_NAME_STAGE }}:${{ env.IMAGE_TAG }}",
      #           "essential": true,
      #           "portMappings": [
      #             {
      #               "containerPort": 3000,
      #               "protocol": "tcp"
      #             }
      #           ]
      #         }
      #       ]
      #     }
      #     EOF

      # - name: Register ECS task definition
      #   id: register-task
      #   run: |
      #     TASK_DEF_ARN=$(aws ecs register-task-definition \
      #       --cli-input-json file://task-def.json \
      #       --query 'taskDefinition.taskDefinitionArn' \
      #       --output text)
      #     echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service to use new task definition
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.TASK_DEF_ARN }}

      - name: Wait for ECS deployment to complete
        run: |
          aws ecs wait services-stable \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }}

      - name: Print ECS deployment status
        run: |
          echo "Deployed to ECS with task: ${{ env.TASK_DEF_ARN }}"
